Arguments: 
  /Users/coop/.nvm/versions/node/v14.19.1/bin/node /Users/coop/.yarn/bin/yarn.js install --lock-file

PATH: 
  /Users/coop/.yarn/bin:/Users/coop/.config/yarn/global/node_modules/.bin:/Users/coop/.nvm/versions/node/v14.19.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/coop/Library/Python/3.9/bin:/Users/coop/.local/bin:/Users/coop/Library/Python/3.9/bin:/Users/coop/.local/bin

Yarn version: 
  1.22.19

Node version: 
  14.19.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/openzeppelin: Not found
      at Request.params.callback [as _callback] (/Users/coop/.yarn/lib/cli.js:66145:18)
      at Request.self.callback (/Users/coop/.yarn/lib/cli.js:140890:22)
      at Request.emit (events.js:400:28)
      at Request.<anonymous> (/Users/coop/.yarn/lib/cli.js:141862:10)
      at Request.emit (events.js:400:28)
      at IncomingMessage.<anonymous> (/Users/coop/.yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (events.js:519:28)
      at IncomingMessage.emit (events.js:412:35)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

npm manifest: 
  {
    "dependencies": {
      "@openzeppelin/contracts": "^4.8.0",
      "@openzeppelin/contracts-upgradeable": "^4.8.0",
      "@openzeppelin/upgrades": "^2.8.0",
      "dotenv": "^16.0.3",
      "hardhat": "^2.12.2",
      "hardhat-contract-sizer": "^2.6.1",
      "hardhat-deploy": "^0.11.20"
    },
    "devDependencies": {
      "@nomicfoundation/hardhat-toolbox": "^2.0.0",
      "openzeppelin": "@openzeppelin/contracts"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
